[{"items": [{"tags": ["tensorflow"], "owner": {"account_id": 8550263, "reputation": 2937, "user_id": 6407393, "user_type": "registered", "accept_rate": 57, "profile_image": "https://www.gravatar.com/avatar/9bb0b98b4ea95c6d68fbe20eedcb7f81?s=256&d=identicon&r=PG&f=1", "display_name": "yanachen", "link": "https://stackoverflow.com/users/6407393/yanachen"}, "is_answered": true, "view_count": 618, "answer_count": 1, "score": 1, "last_activity_date": 1506375716, "creation_date": 1506353065, "question_id": 46408810, "content_license": "CC BY-SA 3.0", "link": "https://stackoverflow.com/questions/46408810/how-to-calculate-auc-in-tensorflow-in-an-easy-way", "title": "How to calculate auc in tensorflow in an easy way?", "body": "<pre><code>sess.run(tf.metrics.auc(labels, preds))\n</code></pre>\n\n<p>I try to use tensorflow to calculate auc. My version is 1.0.\nBut there are some errors.\nAnyone can give an example about how to use it ?\nI see some previous questions but it seems out of date. \nAnyone can give the right codes in the new version ?\n    FailedPreconditionError: Attempting to use uninitialized value auc/false_positives\n             [[Node: auc/false_positives/read = IdentityT=DT_FLOAT, _class=[\"loc:@auc/false_positives\"], _device=\"/job:localhost/replica:0/task:0/cpu:0\"]]</p>\n\n<pre><code>Caused by op u'auc/false_positives/read', defined at:\n  File \"/home/xuemeng.cyn/anaconda2/bin/ipython\", line 6, in &lt;module&gt;\n    sys.exit(IPython.start_ipython())\n  File \"/home/xuemeng.cyn/anaconda2/lib/python2.7/site-packages/IPython/__init__.py\", line 119, in start_ipython\n    return launch_new_instance(argv=argv, **kwargs)\n  File \"/home/xuemeng.cyn/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n    app.start()\n  File \"/home/xuemeng.cyn/anaconda2/lib/python2.7/site-packages/IPython/terminal/ipapp.py\", line 348, in start\n    self.shell.mainloop()\n  File \"/home/xuemeng.cyn/anaconda2/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py\", line 486, in mainloop\n    self.interact()\n  File \"/home/xuemeng.cyn/anaconda2/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py\", line 477, in interact\n    self.run_cell(code, store_history=True)\n  File \"/home/xuemeng.cyn/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py\", line 2717, in run_cell\n    interactivity=interactivity, compiler=compiler, result=result)\n  File \"/home/xuemeng.cyn/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py\", line 2827, in run_ast_nodes\n    if self.run_code(code, result):\n  File \"/home/xuemeng.cyn/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py\", line 2881, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n  File \"&lt;ipython-input-29-2bca3b61757e&gt;\", line 1, in &lt;module&gt;\n    sess.run(tf.metrics.auc(labels, preds))\n  File \"/home/xuemeng.cyn/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/metrics_impl.py\", line 626, in auc\n    labels, predictions, thresholds, weights)\n  File \"/home/xuemeng.cyn/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/metrics_impl.py\", line 544, in _confusion_matrix_at_thresholds\n    false_p = _create_local('false_positives', shape=[num_thresholds])\n  File \"/home/xuemeng.cyn/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/metrics_impl.py\", line 196, in _create_local\n    validate_shape=validate_shape)\n  File \"/home/xuemeng.cyn/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py\", line 1679, in variable\n    caching_device=caching_device, name=name, dtype=dtype)\n  File \"/home/xuemeng.cyn/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variables.py\", line 199, in __init__\n    expected_shape=expected_shape)\n  File \"/home/xuemeng.cyn/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variables.py\", line 330, in _init_from_args\n    self._snapshot = array_ops.identity(self._variable, name=\"read\")\n  File \"/home/xuemeng.cyn/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py\", line 1400, in identity\n    result = _op_def_lib.apply_op(\"Identity\", input=input, name=name)\n  File \"/home/xuemeng.cyn/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py\", line 767, in apply_op\n    op_def=op_def)\n  File \"/home/xuemeng.cyn/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py\", line 2630, in create_op\n    original_op=self._default_original_op, op_def=op_def)\n  File \"/home/xuemeng.cyn/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py\", line 1204, in __init__\n    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access\n\nFailedPreconditionError (see above for traceback): Attempting to use uninitialized value auc/false_positives\n         [[Node: auc/false_positives/read = Identity[T=DT_FLOAT, _class=[\"loc:@auc/false_positives\"], _device=\"/job:localhost/replica:0/task:0/cpu:0\"](auc/false_positives)]]\n</code></pre>\n"}], "has_more": false, "quota_max": 300, "quota_remaining": 95}]