[{"items": [{"tags": ["python", "tensorflow", "keras", "jupyter-notebook", "jupyter"], "owner": {"account_id": 4548208, "reputation": 3430, "user_id": 8089695, "user_type": "registered", "accept_rate": 100, "profile_image": "https://www.gravatar.com/avatar/92107cb1b109e2b8281e9cb76b5e3f16?s=256&d=identicon&r=PG&f=1", "display_name": "MiloMinderbinder", "link": "https://stackoverflow.com/users/8089695/milominderbinder"}, "is_answered": false, "view_count": 42, "answer_count": 0, "score": 1, "last_activity_date": 1559181517, "creation_date": 1559137327, "last_edit_date": 1559181517, "question_id": 56362026, "content_license": "CC BY-SA 4.0", "link": "https://stackoverflow.com/questions/56362026/cannot-import-tensorflow-pretrained-model-multiple-times", "title": "Cannot import tensorflow pretrained model multiple times", "body": "<p>I am trying to use a pre-trained MobileNet for transfer learning however i am running into a problem when i am trying to run the same command the second time</p>\n\n<pre><code>import tensorflow as tf\ntry:\n    del g1\nexcept:\n    pass\ng1 = tf.Graph()\nwith g1.as_default():\n    base_model = tf.keras.applications.MobileNetV2(input_shape=(160,160,3),\n                                                       include_top=False,\n                                                       weights='imagenet')\n</code></pre>\n\n<p>I can run this cell in jupyter alright the first time but the second time i try to run this i get \n<code>TypeError: Cannot interpret feed_dict key as Tensor: Tensor Tensor(\"Placeholder_207:0\", shape=(160,), dtype=float32) is not an element of this graph.</code>\nHowever, I can run this cell multiple times perfectly fine</p>\n\n<pre><code>base_model = tf.keras.applications.MobileNetV2(input_shape=(160,160,3),\n                                                       include_top=False,\n                                                       weights='imagenet')\n</code></pre>\n"}], "has_more": false, "quota_max": 300, "quota_remaining": 172}]