[{"items": [{"tags": ["python", "tensorflow", "keras", "tensorflow2.0", "tf.keras"], "owner": {"account_id": 6956681, "reputation": 1056, "user_id": 5337505, "user_type": "registered", "accept_rate": 67, "profile_image": "https://lh5.googleusercontent.com/-F4WMV67MG-o/AAAAAAAAAAI/AAAAAAAABGA/b-vMtZ0piXI/photo.jpg?sz=256", "display_name": "Siladittya", "link": "https://stackoverflow.com/users/5337505/siladittya"}, "is_answered": true, "view_count": 168, "answer_count": 1, "score": 1, "last_activity_date": 1600333232, "creation_date": 1599759817, "last_edit_date": 1599764176, "question_id": 63835054, "content_license": "CC BY-SA 4.0", "link": "https://stackoverflow.com/questions/63835054/valueerror-strides-should-be-of-length-1-1-or-3-but-was-2-when-using-convlst", "title": "&quot;ValueError: strides should be of length 1, 1 or 3 but was 2&quot; when using ConvLSTM2D", "body": "<p>I have a pre-trained model which has output of shape (20,7,7,256)</p>\n<p>I reshape this output to <code>(None,20,7,7,256)</code> using <code>tf.keras.layers.Reshape((20,7,7,256))</code> and then feed it to a <code>ConvLSTM2D</code> layer</p>\n<pre><code>x = ConvLSTM2D(filters = 256,kernel_size = 3,strides=(1,1),padding='same',\n               data_format = 'channels_last',return_state = True,\n               kernel_initializer=tf.keras.initializers.he_normal(seed=16))(x)\n</code></pre>\n<p>But I get this error every time I run the above code.</p>\n<pre><code>~\\AppData\\Roaming\\Python\\Python38\\site-packages\\tensorflow\\python\\ops\\nn_ops.py in convolution_internal(input, filters, strides, padding, data_format, dilations, name, call_from_convolution)\n    957     channel_index = 1 if data_format.startswith(&quot;NC&quot;) else n + 1\n    958 \n--&gt; 959   strides = _get_sequence(strides, n, channel_index, &quot;strides&quot;)\n    960   dilations = _get_sequence(dilations, n, channel_index, &quot;dilations&quot;)\n    961 \n\n~\\AppData\\Roaming\\Python\\Python38\\site-packages\\tensorflow\\python\\ops\\nn_ops.py in _get_sequence(value, n, channel_index, name)\n     73     value = list(value)\n     74   else:\n---&gt; 75     raise ValueError(&quot;{} should be of length 1, {} or {} but was {}&quot;.format(\n     76         name, n, n + 2, current_n))\n     77 \n\nValueError: strides should be of length 1, 1 or 3 but was 2\n</code></pre>\n<p>What is causing the problem I do not understand, even though I am giving <code>strides = (1,1)</code>?? And what is the solution to this problem?</p>\n<p><strong>EDIT</strong></p>\n<p>THE ERROR WAS NOT IN THIS ConvLSTM2D layer, but it was in the next ConvLSTM2D layer that I added after this one. I used <code>return_state = True</code> in this layer but my intention was to use <code>return_sequences = True</code> and this was causing the error in the next ConvLSTM2D layer.</p>\n<p>The original code is this after changing <code>return_state</code> to <code>return_sequences</code></p>\n<pre><code>x = ConvLSTM2D(filters = 256,kernel_size = 3,\n               strides=(1,1),padding='same',return_sequences = True,\n               kernel_initializer=tf.keras.initializers.he_normal(seed=16))(x)\nx = ConvLSTM2D(filters = 256,kernel_size = 3,\n               strides=(1,1),padding='same',return_sequences = False,\n               kernel_initializer=tf.keras.initializers.he_normal(seed=16))(x)\n</code></pre>\n"}], "has_more": false, "quota_max": 300, "quota_remaining": 24}]