[{"items": [{"tags": ["tensorflow", "keras"], "owner": {"account_id": 7297168, "reputation": 5375, "user_id": 5561472, "user_type": "registered", "accept_rate": 25, "profile_image": "https://i.stack.imgur.com/kf45N.jpg?s=256&g=1", "display_name": "Andrey", "link": "https://stackoverflow.com/users/5561472/andrey"}, "is_answered": true, "view_count": 539, "accepted_answer_id": 65137126, "answer_count": 2, "score": 0, "last_activity_date": 1607049384, "creation_date": 1606933871, "question_id": 65114032, "content_license": "CC BY-SA 4.0", "link": "https://stackoverflow.com/questions/65114032/how-to-concatenate-tensors-after-expanding-dimension-using-keras-functional-api", "title": "How to concatenate tensors after expanding dimension using Keras Functional API?", "body": "<p>I am trying to expand dimension:</p>\n<pre><code>import tensorflow as tf\ninp = tf.keras.layers.Input(shape=(1,))\ninp = inp[..., tf.newaxis]\ndecoder_input = inp\noutput = tf.concat([inp, decoder_input], 1)\nmodel = tf.keras.models.Model(inp, output )\n</code></pre>\n<p>But I get an error in the last line:</p>\n<blockquote>\n<p>Exception has occurred: ValueError Graph disconnected: cannot obtain\nvalue for tensor Tensor(&quot;input_1:0&quot;, shape=(None, 1), dtype=float32)\nat layer &quot;tf_op_layer_strided_slice&quot;. The following previous layers\nwere accessed without issue: []</p>\n</blockquote>\n"}], "has_more": false, "quota_max": 300, "quota_remaining": 17}]