[{"items": [{"tags": ["tensorflow2.0", "kaggle", "tfrecord"], "owner": {"account_id": 2811841, "reputation": 882, "user_id": 2417922, "user_type": "registered", "accept_rate": 0, "profile_image": "https://www.gravatar.com/avatar/5cee40c36bc502473b0976b339a8b8da?s=256&d=identicon&r=PG", "display_name": "Mark Lavin", "link": "https://stackoverflow.com/users/2417922/mark-lavin"}, "is_answered": false, "view_count": 349, "answer_count": 1, "score": 0, "last_activity_date": 1609774248, "creation_date": 1609703202, "question_id": 65554214, "content_license": "CC BY-SA 4.0", "link": "https://stackoverflow.com/questions/65554214/how-do-i-prevent-corrupted-record-in-kaggle-tfrecord-file", "title": "How do I prevent corrupted record in Kaggle TFRecord file?", "body": "<p>I'm attempting to write tiled images to kaggle/working/..., but when I try to re-read the first record to confirm that the write worked, I added the code</p>\n<pre><code>    # Read back one record to confirm:\n    raw_dataset = tf.data.TFRecordDataset( output_path )\n    print( &quot;raw_dataset&quot;, raw_dataset, file = sys.stderr )\n\n    for raw_record in raw_dataset.take(1):\n        example = tf.train.Example()\n        example.ParseFromString(raw_record.numpy())\n        print(&quot;Reading back raw_record from&quot;, output_path, example)\n</code></pre>\n<p>However, I keep getting the error:</p>\n<pre><code>---&gt; 70         for raw_record in raw_dataset.take(1):\n     71             example = tf.train.Example()\n     72             example.ParseFromString(raw_record.numpy())\n     ...\nDataLossError: corrupted record at 0\n</code></pre>\n<p>I have tried several variations, all give the same results. Help!</p>\n"}], "has_more": false, "quota_max": 300, "quota_remaining": 268}]