[{"items": [{"tags": ["python", "tensorflow", "deep-learning", "generator"], "owner": {"account_id": 20425878, "reputation": 13, "user_id": 15050763, "user_type": "registered", "profile_image": "https://lh4.googleusercontent.com/-GB9JpnTqvmc/AAAAAAAAAAI/AAAAAAAAAAA/AMZuucnZMQyRbBCkFvP1CVlf-V_WyDKzoA/s96-c/photo.jpg?sz=256", "display_name": "Aram Harutyunyan", "link": "https://stackoverflow.com/users/15050763/aram-harutyunyan"}, "is_answered": false, "view_count": 158, "answer_count": 1, "score": 0, "last_activity_date": 1612336695, "creation_date": 1612261719, "last_edit_date": 1612265685, "question_id": 66007863, "content_license": "CC BY-SA 4.0", "link": "https://stackoverflow.com/questions/66007863/loading-data-from-generator-using-tf-data-dataset-from-generator", "title": "Loading data from generator using tf.data.Dataset.from_generator()", "body": "<p>I want to load data for my metric learning model, and the data generating function is the <code>get_data()</code>  function</p>\n<pre><code>def get_data():\n    def my_generator():\n        for i in range(10):\n            anchor = list(np.expand_dims(cv2.imread('img1'), axis=0))\n            positive = list(np.expand_dims(cv2.imread('img2'), axis=0)\n            true = 0\n            a = (true, anchor, positive)\n            yield a\n\n    return tf.data.Dataset.from_generator(\n        my_generator,\n        output_types=(tf.int64, tf.Tensor, tf.Tensor),\n        output_shapes=(1, (1, 256, 256, 3), (1, 256, 256, 3))\n    )\n\ndataset = get_data()\n</code></pre>\n<p>when I run this code, I get the following error. I've tried to pass some other arguments to <code>output_types</code>, tf.float64 for example, but it doesn't work either. I think I do something wrong with the shapes, but I can't figure what.</p>\n<blockquote>\n<p>TypeError: Cannot convert value &lt;class 'tensorflow.python.framework.ops.Tensor'&gt; to a TensorFlow DType.</p>\n</blockquote>\n<p>Any help is appreciated :)</p>\n"}], "has_more": false, "quota_max": 300, "quota_remaining": 219}]